### ISSUE TITLE
ingore option not working

### ISSUE THREAD

**Issue by Ajeetlakhani** [ben-eb/gulp-uncss#46] opened 2016-02-09 14:53 UTC
I am trying to ingore user interaction based classes but uncss not ignoring these classes
```javascript
gulp.task('uncss-task', function () {
    return gulp.src(headCss)
      .pipe(expect({ errorOnFailure: true,verbose:true }, headCss))
      .pipe(uncss({
          html: allLinks,
          ignore : [
            '.active',
            '.op-dark',
            '.dialog-overlay',
            ],
      }))
      .pipe(minifyCSS())
      .pipe(gulp.dest('static/gulp-build/styles'))
});
```
tried regex pattern also but it seems not working
```javascript    
      ignore : [
            '/\.active/',
            '/\.op\-dark/',
            '/\.dialog\-overlay/',
            ],
```

**Comment by ben-eb** [comment] 2016-02-09 15:47
Duplicate of https://github.com/ben-eb/gulp-uncss/issues/37

**Closed by ben-eb** 2016-02-09 15:47 UTC
