### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by seanislegend** [ben-eb/gulp-uncss#6] opened 2014-03-28 11:54 UTC
If there's no stylesheets found there is an unhandled error returned.

![screen shot 2014-03-28 at 11 53 19](https://cloud.githubusercontent.com/assets/1477984/2549132/99c6a292-b66f-11e3-928d-867e778ff954.png)

**Comment by mastix** [comment] 2015-03-11 13:48
Hey @ben-eb,

I think I have to re-open this issue.

I have the following (very simple task):

```javascript
gulp.task('removeunusedcss', ['inject', 'partials'], function () {
//the css seen here is not minified or anything like that
  return gulp.src(paths.tmp + '/serve/app/index.css')
    .pipe($.size({title: 'Original Files', showFiles: true}))
    .pipe($.uncss({
      html: [paths.src + '/{app,components}/**/*.html']
    }))
    .pipe(gulp.dest(paths.tmp + '/serve/app/'))
    .pipe($.size({title: 'Removed unused', showFiles: true}));
});
```
This gives me the following output:

    [14:37:58] Finished 'inject' after 440 ms
    [14:37:58] Starting 'removeunusedcss'...
    [14:38:00] 'Original Files' index.css 146.58 kB
    [14:38:00] 'Removed unused' index.css 11.18 kB

    c:\Users\testuser\Development\Projects\Demo-Project\frontend\node_modules\gulp-uncss\node_modules\uncss\node_modules\bluebird\js\main\async.js:36
        fn = function () { throw arg; };
                                 ^
    Error: UnCSS: no stylesheets found
    at process (c:\Users\testuser\Development\Projects\Demo-Project\frontend\node_modules\gulp-uncss\node_modules\uncss\src\uncss.js:145:15)
    at tryCatcher (c:\Users\testuser\Development\Projects\Demo-Project\frontend\node_modules\gulp-uncss\node_modules\uncss\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (c:\Users\testuser\Development\Projects\Demo-Project\frontend\node_modules\gulp-uncss\node_modules\uncss\node_modules\bluebird\js\main\promise.js:452:31)
    at Promise._settlePromiseAt (c:\Users\testuser\Development\Projects\Demo-Project\frontend\node_modules\gulp-uncss\node_modules\uncss\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromises (c:\Users\testuser\Development\Projects\Demo-Project\frontend\node_modules\gulp-uncss\node_modules\uncss\node_modules\bluebird\js\main\promise.js:646:14)
    at Async._drainQueue (c:\Users\testuser\Development\Projects\Demo-Project\frontend\node_modules\gulp-uncss\node_modules\uncss\node_modules\bluebird\js\main\async.js:79:16)
    at Async._drainQueues (c:\Users\testuser\Development\Projects\Demo-Project\frontend\node_modules\gulp-uncss\node_modules\uncss\node_modules\bluebird\js\main\async.js:89:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\testuser\Development\Projects\Demo-Project\frontend\node_modules\gulp-uncss\node_modules\uncss\node_modules\bluebird\js\main\async.js:14:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)


So as you can see in the logs... it actually removes the unused stuff (file size goes down from 146.58 kB to 11.18 kB).

But it fails... in the same task...Is that the same problem mentioned here? Is there anything I'm doing wrong?

Regards,

Sascha

**Comment by ben-eb** [comment] 2015-03-11 14:07
@mastix I don't think you're doing anything wrong, after all this is the expected use case of UnCSS. However I cannot reproduce this failing behaviour, which is frustrating to me... the only suggestion I can make is if you try and come up with a reduced test case that exhibits the same problem and I can take a look at it.

**Comment by mastix** [comment] 2015-03-11 14:15
Hey,

ok... I might have found the issue... when I change 

```javascript
.pipe(gulp.dest(paths.tmp + '/serve/app/'))
```

to

```javascript
.pipe(gulp.dest(paths.tmp + '/serve/app/sometestfolder'))
```

... it works fine. So overwriting the original file seems to be the issue here...

**Comment by mastix** [comment] 2015-03-11 14:21
Ok... now it's weird... I changed it back (removed sometestfolder) and it still works now... really weird...

**Comment by ben-eb** [comment] 2015-03-11 14:56
Are you reading the CSS from a folder where it will only be there temporarily? If so this might just be a race condition where the file has been destroyed before it got to gulp-uncss...

**Comment by ben-eb** [comment] 2015-03-22 22:08
Closing until someone can provide me with a repo that can consistently reproduce this. I've not encountered this problem in my own use cases for gulp-uncss.

**Closed by ben-eb** 2015-03-22 22:08 UTC

**Comment by talymo** [comment] 2015-04-24 15:21
I've found that if I uncss files that are not in nested folders, this works, but as soon as I reach into nested folders I get unexpected behavior. This is only if I already have a build folder though. 

So, to duplicate the issue, create a folder structure similar to this... 
![2015-04-24_1117](https://cloud.githubusercontent.com/assets/6981298/7322056/902d2506-ea73-11e4-8789-88bfc473ec29.png)

Delete the generated build folder you get from your gulp task, then run the gulp file.

You will see that the tasks run with no errors.

Now, run the tasks again. You will see that the task throws the TypeError: 'undefined' is not an object (evaluating t.module) error.

Delete the build folder from your project, build again and it is fine.
