### ISSUE TITLE
Question: is it possible to use gulp-uncss with handlebars precompiled templates?

### ISSUE THREAD

**Issue by samumist** [ben-eb/gulp-uncss#75] opened 2017-01-09 06:28 UTC
Thanks for this great plugin.
I'm wondering if it can work with the handlebars precompiled templates.
I tried to put the handlebar precompiled templates as src like below but it doesn't work.
```
.pipe(plugins.uncss({html: ['dist/index.html', 'dist/js/app.js']}))
```
It doesn't work.

css related to the selectors contained in the `app.js` get 'uncssed'. 

I'm wondering if there's a way to get it work.

Thanks

**Comment by ben-eb** [comment] 2017-07-08 20:09
I think this might be a duplicate of https://github.com/ben-eb/gulp-uncss/issues/82#issue-230958654.

**Closed by ben-eb** 2017-07-08 20:09 UTC
