### ISSUE TITLE
Pass formdata/ login credentials in Uncss

### ISSUE THREAD

**Issue by Ajeetlakhani** [ben-eb/gulp-uncss#44] opened 2016-01-27 16:10 UTC
I need to access the login controlled area of my website. Using phantomjs i can do this but how to do it in uncss ?

**Comment by ben-eb** [comment] 2016-01-27 16:29
Duplicate of https://github.com/giakki/uncss/issues/110 & https://github.com/giakki/uncss/issues/207.

**Closed by ben-eb** 2016-01-27 16:29 UTC
Labels: duplicate, upstream
