### ISSUE TITLE
.cshtml Error: PhantomJs: Cannot open about:blank.

### ISSUE THREAD

**Issue by talymo** [ben-eb/gulp-uncss#29] opened 2015-04-23 21:24 UTC
I am running uncss on a .cshtml file. It works ( it appears to anyway) but it is throwing errors in the output panel during the gulp process. 

I removed repetitive unnecessary path items from the code below to save space and make it easier to read.

The error is as follows: 

..\node_modules\gulp-uncss\node_modules\uncss\node_modules\bluebird\js\main\async.js:43
        fn = function () { throw arg; };
                                 ^
Error: PhantomJS: Cannot open about:blank
    at reject (..\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\lib\phantom\start.js:71)
    at :4
    at :/modules/webpage.js:281
    -----------------------------------------------------------------------
    at Phantom._send (..\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\lib\Phantom.js:165:20)
    at Page.run (..\node_modules\uncss\node_modules\phridge\lib\Page.js:62:25)
    at ..\node_modules\gulp-uncss\node_modules\uncss\src\phantom.js:125:21
    at tryCatchReject (..\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\node_modules\when\lib\makePromise.js:845:30)
    at runContinuation1 (..\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\node_modules\when\lib\makePromise.js:804:4)
    at Fulfilled.when (..\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\node_modules\when\lib\makePromise.js:592:4)
    at Pending.run (..\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\node_modules\when\lib\makePromise.js:483:13)
    at Scheduler._drain (..\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (..\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\node_modules\when\lib\Scheduler.js:27:9)
    at process._tickCallback (node.js:419:13)
Process terminated with code 8.

**Comment by ben-eb** [comment] 2015-04-23 22:08
This is a duplicate of https://github.com/giakki/uncss/issues/150

**Closed by ben-eb** 2015-04-23 22:08 UTC
Labels: duplicate
